/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/usuarios/alta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrar un nuevo usuario individualmente */
        post: operations["altaIndividual"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/alta/masiva": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cargaMasiva"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cursos/crear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["crearCurso"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cursos/crear/masivo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["procesarCargaMasiva"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/cerrar-sesion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cerrarSesion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["buscarUsuarioPorId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/profesores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listarProfesoresResponsables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/listar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listarUsuarios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AltaUsuarioRequest: {
            nombre: string;
            apellido: string;
            /** Format: email */
            correo: string;
            contrasena: string;
            cedula: string;
            /** Format: date */
            fechaNacimiento: string;
            /** @enum {string} */
            rol: "ADMINISTRADOR" | "PROFESOR" | "ESTUDIANTE";
        };
        ErrorLineaCSV: {
            /** Format: int32 */
            linea?: number;
            motivo?: string;
        };
        ResumenCargaMasiva: {
            /** Format: int32 */
            total?: number;
            /** Format: int32 */
            correctos?: number;
            /** Format: int32 */
            errores?: number;
            detalleErrores?: components["schemas"]["ErrorLineaCSV"][];
        };
        CursoCreateRequest: {
            nombre: string;
            codigo: string;
            descripcion: string;
            periodoAcademico: string;
            profesoresResponsables?: components["schemas"]["ProfesorResponsable"][];
        };
        ProfesorResponsable: {
            /** Format: int64 */
            id?: number;
            nombreCompleto?: string;
        };
        Curso: {
            /** Format: int64 */
            id?: number;
            nombre: string;
            codigo: string;
            descripcion: string;
            periodoAcademico: string;
            /** Format: date-time */
            fechaCreacion?: string;
            /** @enum {string} */
            estadoCurso?: "ACTIVO" | "INACTIVO" | "ELIMINADO";
            /** Format: int64 */
            idAdministrador?: number;
            profesoresResponsables?: components["schemas"]["Usuario"][];
        };
        Usuario: {
            /** Format: int64 */
            id?: number;
            nombre: string;
            apellido: string;
            cedula: string;
            /** Format: email */
            correo: string;
            contrasenaHash: string;
            /** @enum {string} */
            estado?: "ACTIVO" | "INACTIVO" | "BLOQUEADO";
            fotoPerfilUrl?: string;
            /** Format: date */
            fechaNacimiento?: string;
            /** Format: date-time */
            fechaCreacion?: string;
            /** Format: date-time */
            ultimoLogin?: string;
            /** Format: int32 */
            intentosFallidos?: number;
            /** @enum {string} */
            rol?: "ADMINISTRADOR" | "PROFESOR" | "ESTUDIANTE";
        };
        InfoCliente: {
            origen?: string;
            ip?: string;
            cliente?: string;
        };
        LoginRequest: {
            correo?: string;
            contrasena?: string;
            infoCliente?: components["schemas"]["InfoCliente"];
        };
        TokenResponse: {
            token?: string;
            /** Format: int64 */
            exp?: number;
            rol?: string;
        };
        CerrarSesionRequest: {
            token?: string;
        };
        UsuarioListadoResponse: {
            /** Format: int64 */
            id?: number;
            nombre?: string;
            apellido?: string;
            cedula?: string;
            correo?: string;
            /** @enum {string} */
            estado?: "ACTIVO" | "INACTIVO" | "BLOQUEADO";
            fotoPerfilUrl?: string;
            /** Format: date */
            fechaNacimiento?: string;
            /** Format: date-time */
            fechaCreacion?: string;
            /** Format: date-time */
            ultimoLogin?: string;
            /** Format: int32 */
            intentosFallidos?: number;
            /** @enum {string} */
            rol?: "ADMINISTRADOR" | "PROFESOR" | "ESTUDIANTE";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    altaIndividual: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AltaUsuarioRequest"];
            };
        };
        responses: {
            /** @description Usuario creado correctamente, sin cuerpo de respuesta */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    cargaMasiva: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    csvFile: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResumenCargaMasiva"];
                };
            };
        };
    };
    crearCurso: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CursoCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Curso"];
                };
            };
        };
    };
    procesarCargaMasiva: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    csvFile: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResumenCargaMasiva"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    cerrarSesion: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CerrarSesionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    buscarUsuarioPorId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    listarProfesoresResponsables: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProfesorResponsable"][];
                };
            };
        };
    };
    listarUsuarios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UsuarioListadoResponse"][];
                };
            };
        };
    };
}
