/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/anuncios/{anuncioId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["actualizar"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/alta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrar un nuevo usuario individualmente */
        post: operations["altaIndividual"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/alta/masiva": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cargaMasiva"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paginas/crear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crea una nueva página temática para un curso (solo profesor responsable) */
        post: operations["crearPagina"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matricula/baja": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["baja"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matricula/baja/masiva": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Desmatriculación masiva por CSV */
        post: operations["bajaMasiva"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matricula/alta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["alta"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matricula/alta/masiva": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Matriculación masiva por CSV */
        post: operations["altaMasiva"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispositivos/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["registrarToken"];
        delete: operations["desactivarToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispositivos/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testPush"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cursos/{cursoId}/recursos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista recursos */
        get: operations["listar"];
        put?: never;
        /** Sube un archivo al curso */
        post: operations["subir"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cursos/eliminar/masivo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["procesarEliminacionMasiva"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cursos/crear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrar un nuevo curso individualmente */
        post: operations["crearCurso"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cursos/crear/masivo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["procesarCargaMasiva"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/cerrar-sesion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cerrarSesion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anuncios/cursos/{cursoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listarPorCurso"];
        put?: never;
        post: operations["crear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca usuario por id, si es administrador devuelve todos los datos */
        get: operations["buscarUsuarioPorId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/profesores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listarProfesoresResponsables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/listar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista todos los usuarios si es administrador */
        get: operations["listarUsuarios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/estudiantes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listarEstudiantes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paginas/listar/{cursoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista todas las páginas visibles de un curso según el rol del usuario */
        get: operations["listarPaginas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cursos/{cursoId}/recursos/{recursoId}/descargar-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Genera URL firmada para descarga */
        get: operations["descargarUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cursos/usuarios-vinculados/{cursoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista todos los usuarios vinculados a un curso dado su id */
        get: operations["obtenerUsuariosVinculados"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cursos/listar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin: lista todos los cursos, Prof o Est: solo los asociados con ellos */
        get: operations["listarCursos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cursos/buscar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca cualquier curso, si es admin muestra todos los datos */
        get: operations["buscarCursos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cursos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["eliminarCurso"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cursos/{cursoId}/recursos/{recursoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Elimina un recurso del curso */
        delete: operations["eliminar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anuncios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["eliminar_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnuncioUpdateRequest: {
            titulo?: string;
            contenido?: string;
            /** Format: date-time */
            fechaProgramada?: string;
        };
        AltaUsuarioRequest: {
            nombre: string;
            apellido: string;
            /** Format: email */
            correo: string;
            contrasena: string;
            cedula: string;
            /** Format: date */
            fechaNacimiento: string;
            /** @enum {string} */
            rol: "ADMINISTRADOR" | "PROFESOR" | "ESTUDIANTE";
        };
        ErrorLineaCSV: {
            /** Format: int32 */
            linea?: number;
            motivo?: string;
        };
        ResumenCargaMasiva: {
            /** Format: int32 */
            total?: number;
            /** Format: int32 */
            correctos?: number;
            /** Format: int32 */
            errores?: number;
            detalleErrores?: components["schemas"]["ErrorLineaCSV"][];
        };
        PaginaCreacionRequest: {
            /** Format: int64 */
            cursoId?: number;
            titulo?: string;
            /** Format: date-time */
            fechaProgramada?: string;
        };
        PaginaResponse: {
            /** Format: int64 */
            id?: number;
            titulo?: string;
            /** Format: date-time */
            fechaProgramada?: string;
            /** Format: date-time */
            fechaCreacion?: string;
            /** Format: int64 */
            cursoId?: number;
            /** Format: int64 */
            creadorId?: number;
        };
        DesmatricularRequest: {
            /** Format: int64 */
            estudianteId?: number;
            /** Format: int64 */
            cursoId?: number;
        };
        MatricularRequest: {
            /** Format: int64 */
            estudianteId?: number;
            /** Format: int64 */
            cursoId?: number;
        };
        RegistrarTokenRequest: {
            token?: string;
            plataforma?: string;
        };
        RecursoSubidaForm: {
            /** @enum {string} */
            ownerRecurso: "PAGINA" | "TAREA" | "ENTREGA";
            /** Format: int64 */
            ownerId: number;
            nombre: string;
            /** Format: binary */
            archivo: string;
        };
        RecursoSubidaResponse: {
            /** Format: int64 */
            id?: number;
            nombreOriginal?: string;
            /** @enum {string} */
            ownerRecurso?: "PAGINA" | "TAREA" | "ENTREGA";
            /** Format: int64 */
            ownerId?: number;
            contentType?: string;
            /** Format: int64 */
            sizeBytes?: number;
            /** Format: date-time */
            fechaSubida?: string;
            /** Format: int64 */
            subidoPorUsuarioId?: number;
        };
        CursoCreateRequest: {
            nombre: string;
            codigo: string;
            descripcion: string;
            periodoAcademico: string;
            profesoresResponsables?: number[];
        };
        Curso: {
            /** Format: int64 */
            id?: number;
            nombre: string;
            codigo: string;
            descripcion: string;
            periodoAcademico: string;
            /** Format: date-time */
            fechaCreacion?: string;
            /** @enum {string} */
            estadoCurso?: "ACTIVO" | "INACTIVO" | "ELIMINADO";
            /** Format: int64 */
            idAdministrador?: number;
            profesoresResponsables?: components["schemas"]["Usuario"][];
        };
        Usuario: {
            /** Format: int64 */
            id?: number;
            nombre: string;
            apellido: string;
            cedula: string;
            /** Format: email */
            correo: string;
            contrasenaHash: string;
            /** @enum {string} */
            estado?: "ACTIVO" | "INACTIVO" | "BLOQUEADO";
            fotoPerfilUrl?: string;
            /** Format: date */
            fechaNacimiento?: string;
            /** Format: date-time */
            fechaCreacion?: string;
            /** Format: date-time */
            ultimoLogin?: string;
            /** Format: int32 */
            intentosFallidos?: number;
            /** @enum {string} */
            rol?: "ADMINISTRADOR" | "PROFESOR" | "ESTUDIANTE";
        };
        LoginRequest: {
            correo?: string;
            contrasena?: string;
        };
        TokenResponse: {
            token?: string;
            /** Format: int64 */
            exp?: number;
            rol?: string;
        };
        AnuncioCreateRequest: {
            titulo: string;
            contenido: string;
            /** Format: date-time */
            fechaProgramada?: string;
        };
        AnuncioResponse: {
            /** Format: int64 */
            id?: number;
            titulo?: string;
            contenido?: string;
            fechaCreacion?: string;
        };
        UsuarioListadoResponse: {
            /** Format: int64 */
            id?: number;
            nombre?: string;
            apellido?: string;
            cedula?: string;
            correo?: string;
            /** @enum {string} */
            estado?: "ACTIVO" | "INACTIVO" | "BLOQUEADO";
            fotoPerfilUrl?: string;
            /** Format: date */
            fechaNacimiento?: string;
            /** Format: date-time */
            fechaCreacion?: string;
            /** Format: date-time */
            ultimoLogin?: string;
            /** Format: int32 */
            intentosFallidos?: number;
            /** @enum {string} */
            rol?: "ADMINISTRADOR" | "PROFESOR" | "ESTUDIANTE";
        };
        EstudianteListadoResponse: {
            nombre?: string;
            apellido?: string;
            cedula?: string;
            correo?: string;
        };
        RecursoListadoResponse: {
            /** Format: int64 */
            id?: number;
            nombreOriginal?: string;
            /** @enum {string} */
            ownerRecurso?: "PAGINA" | "TAREA" | "ENTREGA";
            /** Format: int64 */
            ownerId?: number;
            contentType?: string;
            /** Format: int64 */
            sizeBytes?: number;
            /** Format: date-time */
            fechaSubida?: string;
            /** Format: int64 */
            subidoPorUsuarioId?: number;
        };
        RecursoDescargaResponse: {
            url?: string;
            /** Format: int64 */
            expiraEnSegundos?: number;
        };
        UsuarioVinculadoResponse: {
            /** Format: int64 */
            id?: number;
            nombre?: string;
            apellido?: string;
            correo?: string;
            rol?: string;
        };
        CursoListadoResponse: {
            /** Format: int64 */
            id?: number;
            nombre?: string;
            codigo?: string;
            descripcion?: string;
            periodoAcademico?: string;
            /** @enum {string} */
            estadoCurso?: "ACTIVO" | "INACTIVO" | "ELIMINADO";
            /** Format: date-time */
            fechaCreacion?: string;
            docentesAsignados?: components["schemas"]["DocenteResumen"][];
        };
        DocenteResumen: {
            /** Format: int64 */
            id?: number;
            nombre?: string;
            apellido?: string;
            correo?: string;
        };
        DesactivarTokenRequest: {
            token?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    actualizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                anuncioId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnuncioUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    altaIndividual: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AltaUsuarioRequest"];
            };
        };
        responses: {
            /** @description Usuario creado correctamente, sin cuerpo de respuesta */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    cargaMasiva: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    csvFile: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResumenCargaMasiva"];
                };
            };
        };
    };
    crearPagina: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaginaCreacionRequest"];
            };
        };
        responses: {
            /** @description Página creada correctamente */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaginaResponse"];
                };
            };
        };
    };
    baja: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DesmatricularRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    bajaMasiva: {
        parameters: {
            query: {
                cursoId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    csvFile: string;
                };
            };
        };
        responses: {
            /** @description Carga procesada correctamente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResumenCargaMasiva"];
                };
            };
        };
    };
    alta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatricularRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    altaMasiva: {
        parameters: {
            query: {
                cursoId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    csvFile: string;
                };
            };
        };
        responses: {
            /** @description Carga procesada correctamente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResumenCargaMasiva"];
                };
            };
        };
    };
    registrarToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarTokenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    desactivarToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DesactivarTokenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    testPush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    listar: {
        parameters: {
            query?: {
                ownerRecurso?: "PAGINA" | "TAREA" | "ENTREGA";
                ownerId?: number;
            };
            header?: never;
            path: {
                cursoId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecursoListadoResponse"][];
                };
            };
        };
    };
    subir: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cursoId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["RecursoSubidaForm"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecursoSubidaResponse"];
                };
            };
        };
    };
    procesarEliminacionMasiva: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    csvFile: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResumenCargaMasiva"];
                };
            };
        };
    };
    crearCurso: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CursoCreateRequest"];
            };
        };
        responses: {
            /** @description Curso creado correctamente, sin cuerpo de respuesta */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Curso"];
                };
            };
        };
    };
    procesarCargaMasiva: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    csvFile: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResumenCargaMasiva"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    cerrarSesion: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    listarPorCurso: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cursoId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AnuncioResponse"][];
                };
            };
        };
    };
    crear: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cursoId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnuncioCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AnuncioResponse"];
                };
            };
        };
    };
    buscarUsuarioPorId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    listarProfesoresResponsables: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UsuarioListadoResponse"][];
                };
            };
        };
    };
    listarUsuarios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UsuarioListadoResponse"][];
                };
            };
        };
    };
    listarEstudiantes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EstudianteListadoResponse"][];
                };
            };
        };
    };
    listarPaginas: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cursoId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaginaResponse"][];
                };
            };
        };
    };
    descargarUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cursoId: number;
                recursoId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecursoDescargaResponse"];
                };
            };
        };
    };
    obtenerUsuariosVinculados: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cursoId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UsuarioVinculadoResponse"][];
                };
            };
        };
    };
    listarCursos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CursoListadoResponse"][];
                };
            };
        };
    };
    buscarCursos: {
        parameters: {
            query: {
                id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    eliminarCurso: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    eliminar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cursoId: number;
                recursoId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    eliminar_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
