// Acciones y resultados posibles
export const ACTIONS = [
    "ANUNCIO_CREAR", "ANUNCIO_EDITAR", "ANUNCIO_ELIMINAR",
    "AVATAR_ACTUALIZAR", "AVATAR_RESETEAR",
    "CALIFICACION_CARGA_MASIVA", "CALIFICACION_GUARDAR", "CALIFICACION_PUBLICAR_MASIVA",
    "CUENTA_DESBLOQUEAR",
    "CURSO_CAMBIAR_ESTADO", "CURSO_CARGA_MASIVA", "CURSO_CREAR", "CURSO_EDITAR", "CURSO_ELIMINAR", "CURSO_ELIMINACION_MASIVA", "CURSO_IMAGEN_ACTUALIZAR", "CURSO_IMAGEN_RESETEAR",
    "DESMATRICULA_INDIVIDUAL", "DESMATRICULA_MASIVA",
    "EMAIL_CAMBIO_CONFIRMAR", "EMAIL_CAMBIO_INICIAR",
    "ENTREGA_CORREGIR", "ENTREGA_SUBIR",
    "LOGIN", "LOGOUT",
    "MATRICULA_INDIVIDUAL", "MATRICULA_MASIVA", "MATRICULA_RECHAZADA",
    "MENSAJE_FORO_EDITAR", "MENSAJE_FORO_ELIMINAR", "MENSAJE_FORO_PUBLICAR", "MENSAJE_PRIVADO_ENVIAR",
    "PAGINA_CREAR", "PAGINA_EDITAR", "PAGINA_ELIMINAR",
    "PASSWORD_CAMBIAR", "PASSWORD_RECUPERAR", "PASSWORD_RECUPERAR_REQUEST",
    "PUBLICACION_CREAR", "PUBLICACION_EDITAR", "PUBLICACION_ELIMINAR",
    "RECURSO_ELIMINAR", "RECURSO_SUBIR",
    "TAREA_CREAR", "TAREA_EDITAR", "TAREA_ELIMINAR", "TAREA_ENTREGA_ELIMINAR", "TAREA_ENTREGA_SUBIR",
    "TOKEN_REFRESH",
    "USUARIO_CARGA_MASIVA", "USUARIO_CREAR", "USUARIO_EDITAR"
];

export const RESULTADOS = [
    "EXITO", "ERROR", "EXITO_PARCIAL"
];

export function getTodayDate() {
    return new Date().toISOString().slice(0, 10);
}


export const headers = {
    "Content-Type": "application/json",
    "Cache-Control": "no-store, no-cache, must-revalidate",
    "Pragma": "no-cache",
}